name: teste_eclipse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  flutter_modular: 5.0.3
  lottie: ^2.3.2
  get: ^4.6.5
  intl: 0.17.0
  image_picker:
  share_plus: 6.3.1
  flutter_animated_dialog: ^2.0.1
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
